---
- name: Tp7
  hosts: localhost
  remote_user: root
  become: true
  become_user: root

  tasks:

    - name: Read  CSV file
      community.general.read_csv:
        path: filecsv/temp.csv
        delimiter: ','
      register: data_csv

    - name: Afficher le CSV
      ansible.builtin.debug:
        var: data_csv

    - name: Trier et doublon
      ansible.builtin.set_fact:
        data_csv_clean: "{{ data_csv.list | sort(attribute='time') | unique }}"

    - name: Afficher le CSV trié et dé-doubloné
      ansible.builtin.debug:
        var: data_csv_clean

    - name: Télécharger les données open-meteo
      ansible.builtin.uri:
        url: https://api.open-meteo.com/v1/forecast?latitude=48.86&longitude=2.33&hourly=temperature_2m
      register: openmeteo_data

    - name: Afficher openmeteo
      ansible.builtin.debug:
        var: openmeteo_data