---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-ma.wordpress
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yaml-lint
