- name: tp02
  hosts: all 
  remote_user: root
  become: true
  become_user: root
  vars:
    html_root: /var/www/html
  tasks:

  - name: Install softwares serveur 2 et 3 
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - apache2
      - mysql-server
    when: ansible_facts['nodename'] == "node02" or ansible_facts['nodename'] == "node03"


  - name: check {{ html_root }}
    ansible.builtin.file:
      path: "{{ html_root }}" 
      state: directory

  - name: test the package 
    ansible.builtin.package_facts:
      manager: auto

  - name: Copy index.html if apache2 is installed
    ansible.builtin.template:
        src: template/msg.j2
        dest: /var/www/html/index.html
        mode: '0644'
    when: "'apache2' in ansible_facts.packages"
  


  - name:  Apache start
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: true
    when: ansible_facts['nodename'] == "node02" or ansible_facts['nodename'] == "node03"

 
