---
- name: tp6 
  hosts: web
  become: true
  become_user: root

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.php
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm

  tasks:
  

    - name:  wordpress
      ansible.builtin.unarchive:
        src: https://fr.wordpress.org/wordpress-6.8.1-fr_FR.zip
        dest: /var/www/
        remote_src: true
        creates: /var/www/

    